name = "identity"
license = "MIT"
licenselink = "https://github.com/glyzinie/hugo-identity/blob/main/LICENSE"
description = ""
homepage = "https://github.com/glyzinie/hugo-identity"
tags = []
features = []
min_version = '0.123.0'

[author]
name = "Wis"
homepage = "https://glyzinie.net"
